name: Fetch Netflix verify latest version

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checking and fetching Netflix verify latest version
        run: |
          wget -N https://raw.githubusercontent.com/taffychan/warp/master/.github/nfverify.sh
          bash nfverify.sh
      - name: Git uploading
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Uploaded by Github Actions, Date: $(date)"
          git push
      - name: Refreshing Jsdelivr
        run: |
          curl https://purge.jsdelivr.net/gh/taffychan/warp/netflix/verify/nf_linux_amd64
          curl https://purge.jsdelivr.net/gh/taffychan/warp/netflix/verify/nf_linux_arm64