name: Fetch wgcf latest version to GitLab

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setting GitLab repository
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          # rm -f .git
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          git config --global user.email "misakablog@protonmail.com"
          git config --global user.name "misakablog"
          git clone git@gitlab.com:misakablog/warp-script.git
      - name: Check and fetch wgcf latest version
        run: |
          cd warp-script
          cd files/wgcf
          rm -f wgcf-fetchlog.txt
          actions_date=$(date)
          repo_last_ver=$(curl -Ls "https://api.github.com/repos/ViRb3/wgcf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          repo_ver_name=$(curl -Ls "https://api.github.com/repos/ViRb3/wgcf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed "s/v//g")

          wget -N https://github.com/ViRb3/wgcf/releases/download/$repo_last_ver/wgcf_"$repo_ver_name"_linux_amd64 -O ${GITHUB_WORKSPACE}/files/wgcf/wgcf-latest-linux-amd64
          wget -N https://github.com/ViRb3/wgcf/releases/download/$repo_last_ver/wgcf_"$repo_ver_name"_linux_arm64 -O ${GITHUB_WORKSPACE}/files/wgcf/wgcf-latest-linux-arm64
          wget -N https://github.com/ViRb3/wgcf/releases/download/$repo_last_ver/wgcf_"$repo_ver_name"_linux_s390x -O ${GITHUB_WORKSPACE}/files/wgcf/wgcf-latest-linux-s390x

          cat <<EOF > ${GITHUB_WORKSPACE}/files/logs/wgcf-fetchlog.txt
          # wgcf fetch log generated by GitHub Actions

          Last Version: $repo_last_ver
          Fetch Date: $actions_date
          EOF
      - name: Upload to GitLab
        run: |
          git add .
          git commit -m "Uploaded by Github Actions, Date: $(date)"
          git push